# This is a basic workflow to help you get started with Actions

name: AIP Notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta 
      with: 
        node-version: 14.16.1

    - name: install react and dependencies 
      run:  npm install 
    - name: build the project
      run:  CI="" npm run build
    
    - name: Install Surge
      run: npm install --global surge 

    #run: surge ./build hungry-lumber.surge.sh --token ${{secrets.PUSHNOTIFICATION}}
    - name: Run Surge
      run: surge ./build dramatic-airplane-pushy.surge.sh --token ${{secrets.PUSHNOTIFICATION}}

      name: Install NodeJS
      uses: actions/setup-node@v2-beta 
      with: 
        node-version: 14.16.1